
version: "3"
services:
  pyrog_client:
    image: arkhn/pyrog-client:latest
    container_name: pyrog-client
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file: .env.docker
    restart: "no"