version: '3.7'
services:
  pyrog_client:
    image: arkhn/pyrog-client:latest
    container_name: pyrog-client
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file: .env.docker
    restart: 'no'
    depends_on:
      - cleaning-scripts
    networks:
      - arkhn

  cleaning-scripts:
    image: arkhn/cleaning-scripts:latest
    container_name: cleaning-scripts
    env_file: .env.docker
    ports:
      - 5000:5000
    networks:
      - arkhn

  pagai:
    image: arkhn/pagai:latest
    container_name: pagai
    env_file: .env.docker
    ports:
      - 4000:4000
    networks:
      - arkhn

networks:
  arkhn:
    name: arkhn_network
