version: "3"
services:
  pyrog_client:
    image: arkhn/pyrog-client:latest
    container_name: pyrog-client
    build:
      context: .
    ports:
      - "1729:1729"
    env_file: .env.dev.default
    restart: "no"
