version: "3.7"
services:
  client:
    image: pyrog-client
    container_name: pyrog-client
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file: .env.docker
    restart: "no"
    depends_on:
      - pagai
    networks:
      - arkhn

  pagai:
    image: arkhn/pagai:latest
    container_name: pagai
    env_file: .env.docker
    ports:
      - 4000:4000
    networks:
      - arkhn

networks:
  arkhn:
    name: arkhn_network
