version: '3'
services:
  pyrog_client:
    image: arkhn/pyrog-client:latest
    container_name: pyrog-client
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file: .env.docker
    restart: 'no'
    depends_on:
      - cleaning-scripts

  fhir-pipe:
    image: arkhn/fhir-pipe:latest
    container_name: fhir-pipe
    env_file: .env.docker
    ports:
      - 3000:3000
    networks:
      - arkhn

  cleaning-scripts:
    image: arkhn/cleaning-scripts:latest
    container_name: cleaning-scripts
    env_file: .env.docker
    ports:
      - 5001:5001
