version: '3'
services:
  pyrog_client:
    image: arkhn/pyrog-client:latest
    container_name: pyrog-client
    build:
      context: .
    ports:
      - $PORT:$PORT
    env_file: .env.docker
    restart: 'no'
    depends_on:
      - cleaning-scripts

  cleaning-scripts:
    image: arkhn/cleaning-scripts:latest
    container_name: cleaning-scripts
    env_file: .env.docker
    ports:
      - 5001:5001
