version: "3"
services:
  pyrog-client:
    build:
      context: ./client
    image: arkhn/pyrog2-client:latest
    ports:
      - 1479:1479
    env_file: ./client/.env.docker

  pyrog:
    build:
      context: ./server
    image: arkhn/pyrog2:latest
    ports:
      - 4000:4000
    env_file: ./server/.env.docker
    depends_on:
      - postgres
    volumes:
      - schemas:/home/node/app/schemas

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  schemas:
