version: '3.7'

services:
  pyrog:
    image: pyrog-server
    container_name: pyrog-server
    build:
      context: .
    ports:
      - 1000:1000
    environment:
      - PORT=${PORT:-1000}
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://prisma:prisma@postgres:5432/prisma?schema=pyrog}
      - APP_SECRET=${APP_SECRET:-deadbeefdeadbeefdeadbeefdeadbeef}
      - FHIR_API_URL=${FHIR_API_URL:-https://dev.arkhn.com/api}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ENV=${ENV:-test}
      - DEFINITIONS_DIR=${DEFINITIONS_DIR:-/var/fhir/definitions}
      - PAGAI_URL=${DEFINITIONS_DIR:-https://dev.arkhn.com/pagai}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID:-pyrog-server}
      - OAUTH2_TOKEN_URL=${OAUTH2_TOKEN_URL:-https://dev.arkhn.com/hydra/oauth2/token}
      - TOKEN_INTROSPECTION_URL=${TOKEN_INTROSPECTION_URL:-https://dev.arkhn.com/hydra/oauth2/introspect}
      - USER_INFO_URL==${USER_INFO_URL:-https://dev.arkhn.com/hydra/userinfo}
    volumes:
      - ./definitions:/var/fhir/definitions
    depends_on:
      - postgres
    networks:
      - arkhn

  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - arkhn

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pyrog
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - arkhn

volumes:
  postgres-data:
  schemas:
  redis-data:

networks:
  arkhn:
    name: arkhn_network
