version: '3.7'

services:
  pyrog:
    image: arkhn/pyrog-server:latest
    container_name: pyrog-server
    build:
      context: .
    ports:
      - 1000:1000
    env_file: .env.docker
    depends_on:
      - postgres
    volumes:
      - schemas:/home/node/app/schemas
      - ./backup:/home/node/app/backup
    networks:
      - arkhn

  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - arkhn

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - arkhn

volumes:
  postgres-data:
  schemas:
  redis-data:

networks:
  arkhn:
    name: arkhn_network
