version: '3'
services:
  pyrog:
    image: arkhn/pyrog2:latest
    ports:
      - 4000:4000
    env_file: .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mimic-db:
    env_file: ./mimic/.env
    build:
      context: ./mimic
      dockerfile: MimicPSQL.Dockerfile
      args:
        MIMIC_USER: $MIMIC_USER
        MIMIC_PASSWORD: $MIMIC_PASSWORD
    container_name: fhir-pipe-mimic-db
    restart: always
    volumes:
      - mimic-db:/var/lib/postgresql/data
    ports:
      - '5431:5432'
volumes:
  postgres-data:
  mimic-db:
