version: '3'
services:
  pyrog:
    image: arkhn/pyrog2:latest
    ports:
      - 4000:4000
    environment:
      POSTGRES_URL: 'postgresql://prisma:prisma@postgres:5432/prisma?schema=pyrog'
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
