name: pyrog-client

on: [push]

jobs:
  build:
    name: Build Pyrog client
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version}}-node-modules-${{ hashFiles('client/yarn.lock') }}

      - name: Install Dependencies
        run: |
          cd client
          yarn install

      - name: Build
        run: |
          cd client
          yarn build

  # Same cleaning need to be done, see Issue #105
  #      - name: Lint
  #        run: |
  #          cd client
  #          yarn lint

  publish:
    name: Build and publish
    env:
      GITHUB_REGISTRY: docker.pkg.github.com
      IMAGE: arkhn/pyrog-client
    runs-on: ubuntu-18.04
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: Build staging and demo
        run: |
          cd client/
          yarn build:docker:staging
          yarn build:docker:dev
          yarn build:docker:demo

      - name: Build Ambroise
        env:
          IP: ${{ secrets.IP_VM_AMB }}
          STAGE: ambroise
        run: |
          cd client
          ./scripts/generate_client_env.sh > .env.ambroise
          docker build -t arkhn/pyrog-client:ambroise --build-arg ENV_FILE=.env.ambroise .

      - name: Build AP
        env:
          IP: ${{ secrets.IP_VM_AP }}
          STAGE: aphp
        run: |
          cd client
          ./scripts/generate_client_env.sh > .env.aphp
          docker build -t arkhn/pyrog-client:aphp --build-arg ENV_FILE=.env.aphp .

      - name: Build Clb
        env:
          IP: ${{ secrets.IP_VM_CLB }}
          STAGE: clb
        run: |
          cd client
          ./scripts/generate_client_env.sh > .env.clb
          docker build -t arkhn/pyrog-client:clb --build-arg ENV_FILE=.env.clb .

      - name: Build Curie
        env:
          IP: ${{ secrets.IP_VM_CURIE }}
          STAGE: curie
        run: |
          cd client
          ./scripts/generate_client_env.sh > .env.curie
          docker build -t arkhn/pyrog-client:curie --build-arg ENV_FILE=.env.curie .

      - name: Build RMS
        env:
          IP: ${{ secrets.IP_VM_REIMS }}
          STAGE: rms
        run: |
          cd client
          ./scripts/generate_client_env.sh > .env.rms
          docker build -t arkhn/pyrog-client:rms --build-arg ENV_FILE=.env.rms .

      - name: Tag docker images
        run: |
          docker tag $IMAGE:staging $IMAGE:staging/$GITHUB_SHA
          docker tag $IMAGE:demo $IMAGE:demo/$GITHUB_SHA
          docker tag $IMAGE:dev $IMAGE:dev/$GITHUB_SHA

      - name: Publish to the docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push $IMAGE:staging
          docker push $IMAGE:dev
          docker push $IMAGE:demo
          docker push $IMAGE:$GITHUB_SHA
          docker push $IMAGE:ambroise
          docker push $IMAGE:aphp
          docker push $IMAGE:clb
          docker push $IMAGE:curie
          docker push $IMAGE:rms
