name: pyrog-server

on: [push]

jobs:
  build:
    name: Build Pyrog server
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: server/node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version}}-node-modules-${{ hashFiles('server/yarn.lock') }}

      - name: Install Dependencies
        run: |
          cd server
          yarn install

      - name: Build
        run: |
          cd server
          yarn build

      - name: Lint
        run: |
          cd server
          yarn lint

  publish:
    name: Build and publish
    env:
      GITHUB_REGISTRY: docker.pkg.github.com
      IMAGE: arkhn/pyrog-server
      TAG: latest
    runs-on: ubuntu-18.04
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: |
          cd server/
          yarn build:docker

      - name: Publish to the docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push $IMAGE:$TAG

      - name: Publish to Github Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $GITHUB_REGISTRY -u ${{ github.actor }} --password-stdin
          docker tag $IMAGE:$TAG $GITHUB_REGISTRY/${{ github.repository }}/pyrog-server:$TAG
          docker push $GITHUB_REGISTRY/${{ github.repository }}/pyrog-server:$TAG
